M48
; DRILL file {KiCad (6.0.7-1)-1} date Saturday, February 04, 2023 at 12:54:49 pm
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-04T12:54:49-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X4.498Y-1.6929
X4.498Y-2.3622
X10.2362Y-1.7028
X10.2362Y-2.3622
T0
M30
